// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQIz72AUFDe6h3LZCuOMcLKYzsQEyHi8',
    appId: '1:544137355783:web:3f72a0253066904c6c80a2',
    messagingSenderId: '544137355783',
    projectId: 'kuvioapp',
    authDomain: 'kuvioapp.firebaseapp.com',
    storageBucket: 'kuvioapp.firebasestorage.app',
    measurementId: 'G-K8J2N25KC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_JQm3Ti3mmnu967mSWjWsL_lDTtVhOY',
    appId: '1:544137355783:android:71f205526d0d19186c80a2',
    messagingSenderId: '544137355783',
    projectId: 'kuvioapp',
    storageBucket: 'kuvioapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWqA4bDATfwsSrwrl6cW8HYazCOpEG94c',
    appId: '1:544137355783:ios:42476a057a1025886c80a2',
    messagingSenderId: '544137355783',
    projectId: 'kuvioapp',
    storageBucket: 'kuvioapp.firebasestorage.app',
    iosBundleId: 'com.example.kuvio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWqA4bDATfwsSrwrl6cW8HYazCOpEG94c',
    appId: '1:544137355783:ios:42476a057a1025886c80a2',
    messagingSenderId: '544137355783',
    projectId: 'kuvioapp',
    storageBucket: 'kuvioapp.firebasestorage.app',
    iosBundleId: 'com.example.kuvio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhQIz72AUFDe6h3LZCuOMcLKYzsQEyHi8',
    appId: '1:544137355783:web:ca2e1999c5897b7a6c80a2',
    messagingSenderId: '544137355783',
    projectId: 'kuvioapp',
    authDomain: 'kuvioapp.firebaseapp.com',
    storageBucket: 'kuvioapp.firebasestorage.app',
    measurementId: 'G-TZYM3EFQEQ',
  );
}
